# Generated by Django 3.1.4 on 2024-05-31 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoiosaudeweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='data_hora',
        ),
        migrations.AddField(
            model_name='consulta',
            name='data',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='consulta',
            name='hora',
            field=models.TimeField(default=datetime.time(17, 40, 16, 871378)),
        ),
    ]
