# Generated by Django 3.1.4 on 2024-05-31 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoiosaudeweb', '0002_auto_20240531_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='idade',
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_pics'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='hora',
            field=models.TimeField(verbose_name='hora'),
        ),
    ]
