# Generated by Django 3.1.4 on 2024-05-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoiosaudeweb', '0003_auto_20240531_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='descricao',
            field=models.TextField(default='Descrição não fornecida'),
        ),
    ]
